name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PythonAnywhere API client
      run: pip install pythonanywhere

    - name: Deploy to PythonAnywhere
      run: |
        python -c "
        import pythonanywhere as pa
        user = pa.User('${{ secrets.PYTHONANYWHERE_USERNAME }}', '${{ secrets.PYTHONANYWHERE_API_TOKEN }}')
        user.create_webapp('yuriko992.pythonanywhere.com', python_version='3.11')
        user.webapps['yuriko992.pythonanywhere.com'].add_static_mapping(
            url='/static/', 
            path='/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/yourapp/static/'
        )
        user.webapps['yuriko992.pythonanywhere.com'].add_wsgi_configuration_file(
            '/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/yourapp/wsgi.py'
        )
        user.webapps['yuriko992.pythonanywhere.com'].reload()
        "


