version: '3'
services:
  chatbot:
    image: comp7940-chatbot
    environment:
      - ACCESS_TOKEN_TG=6940947579:AAFMTswa9lwmhP6KzD_QU1B4kxoLvaYN6a0
      - API_KEY=8od4x5TDmaQfn1Wq8lCgHxNxmkL7bwY_97QqDFYuPnI
      - MONGODB_URL=mongodb://daiyuheng:nr4D7LDTfX83PiajBtAEBJ0FAaoDztOxpNQLf5ZpFHJmUBqfw26IwcRV82sUvve0C5NYZpM28BU6ACDbXvfHaQ%3D%3D@daiyuheng.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@daiyuheng@


