name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PythonAnywhere API client
      run: pip install pythonanywhere

    - name: Deploy to PythonAnywhere
      run: |
        python -c "
        import pythonanywhere as pa
        user = pa.User('${{ secrets.PYTHONANYWHERE_USERNAME }}', '${{ secrets.PYTHONANYWHERE_API_TOKEN }}')
        user.create_file('/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/chatbot.py')
        with open('chatbot.py', 'r') as local_file, open(user.files['/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/chatbot.py'], 'w') as pa_file:
            pa_file.write(local_file.read())
        "

    - name: Run bot on PythonAnywhere
      run: |
        python -c "
        import pythonanywhere as pa
        user = pa.User('${{ secrets.PYTHONANYWHERE_USERNAME }}', '${{ secrets.PYTHONANYWHERE_API_TOKEN }}')
        user.run_bash_console_command('python3 chatbot.py')
        "


