name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PYTHONANYWHERE_HOST }}
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          password: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
          source: "."
          target: "/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/"

      - name: Run script
        uses: appleboy/ssh-action@master
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          ACCESS_TOKEN_TG: ${{ secrets.ACCESS_TOKEN_TG }}
        with:
          host: ${{ secrets.PYTHONANYWHERE_HOST }}
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          password: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
          script: python3 /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/chatbot.py


