name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PYTHONANYWHERE_HOST }}
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          password: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
          source: "."
          target: "/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/"

      - name: Restart Always-On Task
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PYTHONANYWHERE_HOST }}
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          password: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
          script: |
            curl -H "Authorization: Token ${PYTHONANYWHERE_API_TOKEN}" -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/always-on/restart/
  
  
