name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install requests module
      run: pip install requests

    - name: Deploy to PythonAnywhere
      run: |
        python -c "
        import requests

        username = '${{ secrets.PYTHONANYWHERE_USERNAME }}'
        api_token = '${{ secrets.PYTHONANYWHERE_API_TOKEN }}'
        domain_name = 'yuriko992.pythonanywhere.com'
        python_version = '3.11'

        response = requests.post(
            f'https://www.pythonanywhere.com/api/v0/user/{username}/webapps/{domain_name}/',
            headers={'Authorization': f'Token {api_token}'},
            data={'python_version': python_version}
        )

        # Check if the web app was created successfully
        if response.status_code == 201:
            print('Web app created successfully')
        else:
            print(f'Failed to create web app: {response.content}')

        "



